#!/bin/sh

git config --global alias.ci commit
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.st status

git config --global core.excludesfile /stash/conf/git/gitignore_global
